SET DATABASE SQL SYNTAX ORA TRUE;

create table DATABUS_LAST_EVENT_READ (
  TABLE_NAME VARCHAR2(50) not null,
  SEC        NUMBER not null,
  EVENT_DATE DATE not null
);

CREATE TABLE DATABUS_EVENT (
	EVENT_DATE DATE NOT NULL ,
	SEC NUMBER NOT NULL ,
	ORIGEN VARCHAR2(50) NOT NULL ,
	TIPO_EVENTO VARCHAR2(30) NOT NULL ,
	CAMPO_MODIF VARCHAR2(512),
	PKS VARCHAR2(50) NOT NULL ,
	VA_VN VARCHAR2(512),
	PAYLOAD VARCHAR2(4000) NOT NULL ,
	PROCESSED NUMBER(1,0) DEFAULT 0
);
